import numpy as np
from scipy.optimize import least_squares

from properties import state_from_TP
from components.compressor import Compressor
from components.turbine import Turbine
from components.heat_exchanger import TemperatureTargetHeatExchanger
from cycles.DischargeCycle import DischargeCycle
from cycles.ChargeCycle import ChargeCycle
from plots import plot_ts_diagram


# ============================================================
# Helpers
# ============================================================

def C_to_K(T_C):
    return T_C + 273.15

def K_to_C(T_K):
    return T_K - 273.15


# ============================================================
# Fixed inputs
# ============================================================

eta_comp = 0.9
eta_turb = 0.9

# Charge boundary temperatures of working fluid
T_comp_in_chg = C_to_K(400.0)
T_turb_in_chg = C_to_K(30.0)

# Nominal values used as initial guess
P_low_chg_nom = 8e6
beta_chg_nom = 3.06

P_low_dischg_nom = 8e6
beta_dischg_nom = 3.26

TTD_nom = 5.0


# ============================================================
# Charge model
# ============================================================

def run_charge(P_low_chg, beta_chg, TTD_hot_chg, TTD_cold_chg,TTD_reject_chg):
    P_high_chg = P_low_chg * beta_chg

    state_1 = state_from_TP(T=T_comp_in_chg, P=P_low_chg)
    state_3 = state_from_TP(T=T_turb_in_chg, P=P_high_chg)

    compressor = Compressor(
        eta=eta_comp,
        P_out=P_high_chg
    )

    turbine = Turbine(
        eta=eta_turb,
        P_out=P_low_chg
    )

    hot_hx = TemperatureTargetHeatExchanger(
        approach_temp=TTD_hot_chg
    )

    cold_hx = TemperatureTargetHeatExchanger(
        approach_temp=TTD_cold_chg
    )

    cycle = ChargeCycle(
        compressor=compressor,
        turbine=turbine,
        hot_hx=hot_hx,
        cold_hx=cold_hx
    )

    results = cycle.solve(
        state_1=state_1,
        state_3=state_3,
        TTD_reject=TTD_reject_chg
    )

    temps = results["TES_temperatures"]

    return {
        "results": results,

        # Initial tank levels seen by charge
        "T_HL": temps["T_low_hotTES_in"],
        "T_CH": temps["T_high_ColdTES_in"],

        # New temperatures generated by charge
        "T_HH": temps["T_high_HotTES_out"],
        "T_CL": temps["T_low_ColdTES_out"],
    }


# ============================================================
# Discharge model
# ============================================================

def run_discharge(P_low_dischg, beta_dischg,
                  T_HH, T_CL,
                  TTD_hot_dischg, TTD_cold_dischg,TTD_reject_dischg):

    P_high_dischg = P_low_dischg * beta_dischg

    # WF temperatures imposed by the TES temperatures + TTD
    T1_wf = T_CL + TTD_cold_dischg
    T3_wf = T_HH - TTD_hot_dischg

    if T1_wf <= 200.0 or T3_wf <= 200.0:
        raise ValueError("Invalid discharge WF temperature.")

    if T3_wf <= T1_wf:
        raise ValueError("Discharge turbine inlet temperature lower than compressor inlet temperature.")

    state_1 = state_from_TP(T=T1_wf, P=P_low_dischg)
    state_3 = state_from_TP(T=T3_wf, P=P_high_dischg)

    compressor = Compressor(
        eta=eta_comp,
        P_out=P_high_dischg
    )

    turbine = Turbine(
        eta=eta_turb,
        P_out=P_low_dischg
    )

    cycle = DischargeCycle(
        compressor=compressor,
        turbine=turbine
    )

    results = cycle.solve(
        state_1=state_1,
        state_3=state_3,
        TTD_reject=TTD_reject_dischg
    )

    state_2 = results["states"]["2"]
    state_4 = results["states"]["4"]

    # TES temperatures implied after discharge
    T_HL_after = state_2.T + TTD_hot_dischg
    T_CH_after = state_4.T - TTD_cold_dischg

    return {
        "results": results,
        "T_HL_after": T_HL_after,
        "T_CH_after": T_CH_after,
        "T1_wf": T1_wf,
        "T3_wf": T3_wf,
    }


# ============================================================
# Target initial tank temperatures
# ============================================================
# Opción A:
# Usar la carga nominal solo para generar un target inicial consistente.
# Después puedes reemplazar T_HL0 y T_CH0 por los valores que tú quieras probar.

nominal_charge = run_charge(
    P_low_chg=P_low_chg_nom,
    beta_chg=beta_chg_nom,
    TTD_hot_chg=TTD_nom,
    TTD_cold_chg=TTD_nom,
    TTD_reject_chg=TTD_nom
)

T_HL0 = nominal_charge["T_HL"]   # Hot-low initial target
T_CH0 = nominal_charge["T_CH"]   # Cold-high initial target

# Opción B:
# Si quieres imponer tus propias temperaturas iniciales, comenta lo de arriba
# y descomenta algo como esto:
#
# T_HL0 = C_to_K(XXX)   # hot-low inicial que tú quieres
# T_CH0 = C_to_K(YYY)   # cold-high inicial que tú quieres


print("Target tank temperatures:")
print(f"T_HL0 hot-low initial   = {K_to_C(T_HL0):.2f} °C")
print(f"T_CH0 cold-high initial = {K_to_C(T_CH0):.2f} °C")


# ============================================================
# Full Level 3 residual
# ============================================================

x_nom = np.array([
    P_low_chg_nom,
    beta_chg_nom,
    P_low_dischg_nom,
    beta_dischg_nom,
    TTD_nom,
    TTD_nom,
    TTD_nom,
    TTD_nom,
    TTD_nom,   # TTD_reject_chg
    TTD_nom,   # TTD_reject_dischg
], dtype=float)

x_scale_solver = np.array([
    1e7,
    1.0,
    1e7,
    1.0,
    10.0,
    10.0,
    10.0,
    10.0,
    10.0,
    10.0,
], dtype=float)

T_scale = 10.0
regularization_weight = 1e-4
BIG = 1e6


def full_temperature_closure_residuals(x):
    (
        P_low_chg,
        beta_chg,
        P_low_dischg,
        beta_dischg,
        TTD_hot_chg,
        TTD_cold_chg,
        TTD_hot_dischg,
        TTD_cold_dischg,
        TTD_reject_chg,
        TTD_reject_dischg,
    ) = x

    try:
        chg = run_charge(
            P_low_chg=P_low_chg,
            beta_chg=beta_chg,
            TTD_hot_chg=TTD_hot_chg,
            TTD_cold_chg=TTD_cold_chg,
            TTD_reject_chg=TTD_reject_chg,
        )

        T_HL_chg = chg["T_HL"]
        T_CH_chg = chg["T_CH"]

        T_HH = chg["T_HH"]
        T_CL = chg["T_CL"]

        dis = run_discharge(
            P_low_dischg=P_low_dischg,
            beta_dischg=beta_dischg,
            T_HH=T_HH,
            T_CL=T_CL,
            TTD_hot_dischg=TTD_hot_dischg,
            TTD_cold_dischg=TTD_cold_dischg,
            TTD_reject_dischg=TTD_reject_dischg,
        )

        T_HL_dis = dis["T_HL_after"]
        T_CH_dis = dis["T_CH_after"]

        # Main physical residuals: tank temperature closure
        r_temperature = np.array([
            (T_HL_chg - T_HL0) / T_scale,
            (T_CH_chg - T_CH0) / T_scale,
            (T_HL_dis - T_HL0) / T_scale,
            (T_CH_dis - T_CH0) / T_scale,
        ])

        # Weak regularization: chooses a reasonable solution among many possible ones
        r_regularization = regularization_weight * ((x - x_nom) / x_scale_solver)

        return np.concatenate([r_temperature, r_regularization])

    except Exception:
        return BIG * np.ones(12)


# ============================================================
# Solver
# ============================================================

guess = x_nom.copy()

lower_bounds = np.array([
    8.0e6,   # P_low_chg min
    2.05,    # beta_chg min
    8.0e6,   # P_low_dischg min
    2.05,    # beta_dischg min
    5.0,     # TTD_hot_chg min
    5.0,     # TTD_cold_chg min
    5.0,     # TTD_hot_dischg min
    5.0,     # TTD_cold_dischg min
    2.0,     # TTD_reject_chg min
    2.0,     # TTD_reject_dischg min
], dtype=float)

upper_bounds = np.array([
    9e6,    # P_low_chg max
    4.0,    # beta_chg max
    9e6,    # P_low_dischg max
    4.0,    # beta_dischg max
    50.0,    # TTD_hot_chg max
    50.0,    # TTD_cold_chg max
    50.0,    # TTD_hot_dischg max
    50.0,    # TTD_cold_dischg max
    50.0,    # TTD_reject_chg max
    50.0,    # TTD_reject_dischg max
], dtype=float)

solution = least_squares(
    full_temperature_closure_residuals,
    x0=guess,
    bounds=(lower_bounds, upper_bounds),
    x_scale=x_scale_solver,
    ftol=1e-10,
    xtol=1e-10,
    gtol=1e-10,
    max_nfev=1000,
    verbose=2,
)

x_sol = solution.x

(
    P_low_chg_sol,
    beta_chg_sol,
    P_low_dischg_sol,
    beta_dischg_sol,
    TTD_hot_chg_sol,
    TTD_cold_chg_sol,
    TTD_hot_dischg_sol,
    TTD_cold_dischg_sol,
    TTD_reject_chg_sol,
    TTD_reject_dischg_sol,
) = x_sol

P_high_chg_sol = P_low_chg_sol * beta_chg_sol
P_high_dischg_sol = P_low_dischg_sol * beta_dischg_sol


# ============================================================
# Evaluate final solution
# ============================================================

chg_sol = run_charge(
    P_low_chg=P_low_chg_sol,
    beta_chg=beta_chg_sol,
    TTD_hot_chg=TTD_hot_chg_sol,
    TTD_cold_chg=TTD_cold_chg_sol,
    TTD_reject_chg=TTD_reject_chg_sol,
)

dis_sol = run_discharge(
    P_low_dischg=P_low_dischg_sol,
    beta_dischg=beta_dischg_sol,
    T_HH=chg_sol["T_HH"],
    T_CL=chg_sol["T_CL"],
    TTD_hot_dischg=TTD_hot_dischg_sol,
    TTD_cold_dischg=TTD_cold_dischg_sol,
    TTD_reject_dischg=TTD_reject_dischg_sol,
)

T_HL_chg_sol = chg_sol["T_HL"]
T_CH_chg_sol = chg_sol["T_CH"]
T_HH_sol = chg_sol["T_HH"]
T_CL_sol = chg_sol["T_CL"]

T_HL_dis_sol = dis_sol["T_HL_after"]
T_CH_dis_sol = dis_sol["T_CH_after"]


print("\n============================================================")
print("LEVEL 3 SOLUTION")
print("============================================================")

print("\nCharge pressures:")
print(f"P_low_chg   = {P_low_chg_sol/1e6:.4f} MPa")
print(f"P_high_chg  = {P_high_chg_sol/1e6:.4f} MPa")
print(f"beta_chg    = {beta_chg_sol:.4f}")

print("\nDischarge pressures:")
print(f"P_low_dischg   = {P_low_dischg_sol/1e6:.4f} MPa")
print(f"P_high_dischg  = {P_high_dischg_sol/1e6:.4f} MPa")
print(f"beta_dischg    = {beta_dischg_sol:.4f}")

print("\nTTDs:")
print(f"TTD_hot_chg      = {TTD_hot_chg_sol:.4f} K")
print(f"TTD_cold_chg     = {TTD_cold_chg_sol:.4f} K")
print(f"TTD_hot_dischg   = {TTD_hot_dischg_sol:.4f} K")
print(f"TTD_cold_dischg  = {TTD_cold_dischg_sol:.4f} K")
print(f"TTD_reject_chg      = {TTD_reject_chg_sol:.4f} K")
print(f"TTD_reject_dischg   = {TTD_reject_dischg_sol:.4f} K")

print("\nTank temperatures by stage:")
print("============================================================")

print("\nBefore charge:")
print(f"Hot high tank   = not generated / empty")
print(f"Hot low tank    = {K_to_C(T_HL0):.4f} °C")
print(f"Cold high tank  = {K_to_C(T_CH0):.4f} °C")
print(f"Cold low tank   = not generated / empty")

print("\nAfter charge:")
print(f"Hot high tank   = {K_to_C(T_HH_sol):.4f} °C")
print(f"Hot low tank    = {K_to_C(T_HL_chg_sol):.4f} °C")
print(f"Cold high tank  = {K_to_C(T_CH_chg_sol):.4f} °C")
print(f"Cold low tank   = {K_to_C(T_CL_sol):.4f} °C")

print("\nAfter discharge:")
print(f"Hot high tank   = used / depleted, temperature level was {K_to_C(T_HH_sol):.4f} °C")
print(f"Hot low tank    = {K_to_C(T_HL_dis_sol):.4f} °C")
print(f"Cold high tank  = {K_to_C(T_CH_dis_sol):.4f} °C")
print(f"Cold low tank   = used / depleted, temperature level was {K_to_C(T_CL_sol):.4f} °C")

print("\nClosure errors:")
print(f"Hot low error after charge       = {T_HL_chg_sol - T_HL0:.6e} K")
print(f"Cold high error after charge     = {T_CH_chg_sol - T_CH0:.6e} K")
print(f"Hot low error after discharge    = {T_HL_dis_sol - T_HL0:.6e} K")
print(f"Cold high error after discharge  = {T_CH_dis_sol - T_CH0:.6e} K")

print()
print(f"T_CH0 target cold-high        = {K_to_C(T_CH0):.4f} °C")
print(f"T_CH from charge              = {K_to_C(T_CH_chg_sol):.4f} °C")
print(f"T_CH after discharge          = {K_to_C(T_CH_dis_sol):.4f} °C")

print()
print(f"T_HH generated by charge      = {K_to_C(T_HH_sol):.4f} °C")
print(f"T_CL generated by charge      = {K_to_C(T_CL_sol):.4f} °C")

print("\nUnscaled tank-temperature residuals:")
print(f"T_HL_charge - T_HL0      = {T_HL_chg_sol - T_HL0:.6e} K")
print(f"T_CH_charge - T_CH0      = {T_CH_chg_sol - T_CH0:.6e} K")
print(f"T_HL_discharge - T_HL0   = {T_HL_dis_sol - T_HL0:.6e} K")
print(f"T_CH_discharge - T_CH0   = {T_CH_dis_sol - T_CH0:.6e} K")

print("\nSolver info:")
print("success:", solution.success)
print("message:", solution.message)
print("cost:", solution.cost)

results_chg = chg_sol["results"]
results_dischg = dis_sol["results"]

plot_ts_diagram(results_chg, results_dischg)

roundtrip_efficiency = results_dischg["specific_quantities"]["w_net_per_kg"] / results_chg["specific_quantities"]["w_net_per_kg"]
print(f"Roundtrip efficiency: {roundtrip_efficiency:.2%}")

thermal_efficiency = results_dischg["specific_quantities"]["w_net_per_kg"] / abs(results_dischg["specific_quantities"]["q_hot_per_kg"])
print(f"Thermal efficiency: {thermal_efficiency:.2%}")

COP_charge_heat = abs(results_chg["specific_quantities"]["q_hot_per_kg"]) / results_chg["specific_quantities"]["w_net_per_kg"] 
print(f"COP of charge cycle (heat): {COP_charge_heat:.2f}")

COP_charge_cool = abs(results_chg["specific_quantities"]["q_cold_per_kg"]) / results_chg["specific_quantities"]["w_net_per_kg"]
print(f"COP of charge cycle (cool): {COP_charge_cool:.2f}")

work_ratio = results_chg["specific_quantities"]["w_comp_per_kg"] / results_chg["specific_quantities"]["w_turb_per_kg"]
print(f"Work ratio: {work_ratio:.2f}")